settings:
  legacy:
    force: false
    interval: 0s
server:
  status: true
schema:
  - name: go-gin
    path: .
    commands:
      install:
        status: true
        method: go build -o go/bin/go-gin
      run:
        status: true
        method: go/bin/go-gin
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
        - .history
